using System;
using System.Collections.Generic;

namespace SIDES.EFCoreModels.ScafffoldEntities.Persistance
{
    public partial class QuestionAnswer
    {
        public int QuestionAnswerId { get; set; }
        public int EmployeeId { get; set; }
        public string? Name { get; set; }
        public int? Lengthofemploymentid { get; set; }
        public string? Jobtitle { get; set; }
        public string? Terminationdate { get; set; }
        public string? Managername { get; set; }
        public string? Departmentname { get; set; }
        public int? ReasonForSeparationId { get; set; }
        public string? Benefits { get; set; }
        public string? Salary { get; set; }
        public string? Communicationwithsupervisors { get; set; }
        public string? Levelofcommunication { get; set; }
        public string? Organizationalsupport { get; set; }
        public string? Workenvironment { get; set; }
        public string? Myachievements { get; set; }
        public string? Myskills { get; set; }
        public string? Training { get; set; }
        public string? Relocating { get; set; }
        public string? Promotion { get; set; }
        public string? Retiring { get; set; }
        public string? Shortercommute { get; set; }
        public string? Backtoschool { get; set; }
        public string? Unhappy { get; set; }
        public string? Compensation { get; set; }
        public string? Newtechnology { get; set; }
        public string? Newposition { get; set; }
        public string? Factors { get; set; }
        public string? Ishealthcare { get; set; }
        public string? Manageravailability { get; set; }
        public string? Manageravailabilitycomments { get; set; }
        public string? Achievementsrecognition { get; set; }
        public string? Achievementsrecognitioncomments { get; set; }
        public string? Issueresolution { get; set; }
        public string? Issueresolutioncomments { get; set; }
        public string? Policyapplication { get; set; }
        public string? Policyapplicationcomments { get; set; }
        public string? Clearexpectations { get; set; }
        public string? Clearexpectationscomments { get; set; }
        public string? Coachingmentoring { get; set; }
        public string? Coachingmentoringcomments { get; set; }
        public string? Trainingongoing { get; set; }
        public string? Trainingongoingcomments { get; set; }
        public string? Communicationdepartment { get; set; }
        public string? Communicationdepartmentcomments { get; set; }
        public string? Communicationinterdepartmental { get; set; }
        public string? Communicationinterdepartmentalcomments { get; set; }
        public string? Basesalary { get; set; }
        public string? Basesalarycomments { get; set; }
        public string? Bonus { get; set; }
        public string? Bonuscomments { get; set; }
        public string? Opportunityadvancement { get; set; }
        public string? Opportunityadvancementcomments { get; set; }
        public string? Performanceprocess { get; set; }
        public string? Performanceprocesscomments { get; set; }
        public string? Salaryreviews { get; set; }
        public string? Salaryreviewscomments { get; set; }
        public string? Benefitscoverage { get; set; }
        public string? Benefitscoveragecomments { get; set; }
        public string? Benefitscost { get; set; }
        public string? Benefitscostcomments { get; set; }
        public string? Culture { get; set; }
        public string? Culturecomments { get; set; }
        public string? Comfortableopinions { get; set; }
        public string? Employmentconcerns { get; set; }
        public string? Natureofconcern { get; set; }
        public string? Sharedconcerns { get; set; }
        public string? Followedupconcerns { get; set; }
        public string? Whetherresolved { get; set; }
        public string? Whynot { get; set; }
        public string? Compliancehotline { get; set; }
        public string? Easyresources { get; set; }
        public string? Effectiveskills { get; set; }
        public string? Accuratepicture { get; set; }
        public string? Discrepancies { get; set; }
        public string? Improvement { get; set; }
        public string? Worktogether { get; set; }
        public string? Listensupervisor { get; set; }
        public string? Departmentcommunications { get; set; }
        public string? Helporganization { get; set; }
        public string? Accomplishmentpart { get; set; }
        public string? Problememployment { get; set; }
        public string? Problememploymentcomments { get; set; }
        public string? Recognizedcontributions { get; set; }
        public string? Eventresponsible { get; set; }
        public string? Eventresponsiblecomments { get; set; }
        public string? Employerscale { get; set; }
        public string? Employerscalecomment { get; set; }
        public DateTime Datecreated { get; set; }
        public string? Returningtowork { get; set; }
        public string? Returningtoworkcomments { get; set; }
        public string? Livestoitsvalues { get; set; }
        public string? Livestoitsvaluescomments { get; set; }
        public string? Missionandcause { get; set; }
        public string? Missionandcausecomments { get; set; }
        public string? Knowledge { get; set; }
        public string? Knowledgecomments { get; set; }
        public string? LikeJobComments { get; set; }
        public string? DislikeJobComments { get; set; }
        public string? Coworkersfeeling { get; set; }
        public string? Coworkersfeelingcomments { get; set; }
        public string? RetainemployeeComments { get; set; }
        public string? YourSupervisor { get; set; }
        public string? ManagerDepartment { get; set; }
        public string? HumanResourcesRepresentative { get; set; }
        public string? ConcernComments { get; set; }
        public string? Performancereviewprocess { get; set; }
        public string? Moraleoverall { get; set; }
        public string? Moralearea { get; set; }
        public string? Excellentservice { get; set; }
        public string? Ymcamissioninvolvement { get; set; }
        public string? Mentoring { get; set; }
        public string? TrainingOpportunities { get; set; }
        public string? AdheredtoPolicy { get; set; }
        public string? CommunicatedPolicy { get; set; }
        public string? CommunicatedDepartment { get; set; }
        public string? PerformanceReviews { get; set; }
        public string? EquitableTreatment { get; set; }
        public string? Corevalues { get; set; }
        public string? EncouragedFeedback { get; set; }
        public string? ClearDirections { get; set; }
        public string? PerformanceFeedback { get; set; }
        public string? ResolvedIssues { get; set; }
        public string? ProfessionalGrowth { get; set; }
        public string? ValuedSuggestions { get; set; }
        public string? AdvancementPotential { get; set; }
        public string? BranchManagement { get; set; }
        public string? ClarityofRoles { get; set; }
        public string? CoworkerRelationships { get; set; }
        public string? DirectionoftheAssociation { get; set; }
        public string? EmployeeMorale { get; set; }
        public string? Equipmentandresources { get; set; }
        public string? Immediatesupervisor { get; set; }
        public string? InterestingWork { get; set; }
        public string? Orientation { get; set; }
        public string? Workload { get; set; }
        public string? TypeofWorkComments { get; set; }
        public string? NewJobComments { get; set; }
        public string? TypeOfJobIndustryComments { get; set; }
        public string? FamilyCircumstances { get; set; }
        public string? Illness { get; set; }
        public string? NewJob { get; set; }
        public string? Layoff { get; set; }
        public string? LimitedAdvancement { get; set; }
        public string? Maternity { get; set; }
        public string? Notchallenged { get; set; }
        public string? Pay { get; set; }
        public string? Conflictswithpeers { get; set; }
        public string? Conflictswithsupervisor { get; set; }
        public string? TypeofWork { get; set; }
        public string? BenefitsOffered { get; set; }
        public string? UpperManagementsActions { get; set; }
        public string? WorkingConditions { get; set; }
        public string? WorkHours { get; set; }

        public virtual Employee Employee { get; set; } = null!;
        public virtual LengthofEmployment? Lengthofemployment { get; set; }
        public virtual ReasonForSeparation? ReasonForSeparation { get; set; }
    }
}
